env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:solid/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - solid
  - only-warn
rules:
  import/extensions: off
  import/no-unresolved: off
  solid/jsx-no-undef: off
  import/no-extraneous-dependencies: off
  no-undef: off
  no-plusplus: off
  eqeqeq: off
  no-unused-vars: off
  no-param-reassign: off
  consistent-return: off
  no-underscore-dangle: off
